import type { Vehicle } from '@entities/vehicle/model/types';

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'v1',
    vehicle_number: 'MH01AB1234',
    oem: 'Tata',
    model: 'Nexon EV',
    type_of_vehicle: 'SUV',
    engine_type: 'EV',
    hub_id: 'hub1',
    category: 'M1',
    chassis_number: 'CH123456',
    city_code: 'MUM',
    country_code: 'IN',
    created_at: '2023-01-01',
    updated_at: '2023-01-01',
    fastag_account: 'AC123',
    fastag_number: 'FT123',
    financier_name: 'HDFC',
    fitness: { expiry_date: '2025-01-01', status: 'Valid' },
    generation: '2023',
    insurance: {
        insurance_type: 'Comprehensive',
        insurer_broker: 'Broker1',
        insurer_name: 'Insurance1',
        policy_end_date: '2024-01-01',
        policy_number: 'POL123',
        policy_start_date: '2023-01-01',
        premium_amount: 10000,
    },
    invoice_date: '2023-01-01',
    lease_end_date: null,
    lease_start_date: null,
    leasing_entity: null,
    ownership_count: 1,
    ownership_type: 'Owned',
    powertrain_specs: {
        ev: {
            arai_range_km: 312,
            battery_capacity_kwh: 30.2,
            battery_soh_date: '2023-01-01',
            battery_soh_percent: 100,
            battery_type: 'Li-ion',
            connector_type: 'CCS2',
            current_range_km: 300,
            fast_charger_rate_kw: 50,
            onboard_charger_capacity_kw: 3.3,
            range_on_start_date_km: 312,
        }
    },
    puc_expiry_date: '2024-01-01',
    registration_date: '2023-01-01',
    service_config: {
        alert_interval_days: 30,
        automatic_climate_control: true,
        preventive_service_interval_days: 180,
        preventive_service_km: 10000,
        preventive_service_trigger_type: 'km',
        stepney_count: 1,
        stepney_size: 'R16',
        tyre_replacement_km: 40000,
        tyre_size: 'R16',
        wheel_alignment_km_alert_range: 5000,
    },
    state_code: 'MH',
    telematics: { enabled: true, type: 'GPS', name: 'Tel1' },
    toll: { amount: 0, scope: 'National', type: 'Tag', validity_date: '2024-01-01' },
    variant: 'XZ+',
    warranties: [],
  },
  {
    id: 'v2',
    vehicle_number: 'DL01XY9876',
    oem: 'Maruti',
    model: 'Swift',
    type_of_vehicle: 'Hatchback',
    engine_type: 'Petrol',
    hub_id: 'hub2',
    category: 'M1',
    chassis_number: 'CH987654',
    city_code: 'DEL',
    country_code: 'IN',
    created_at: '2022-01-01',
    updated_at: '2022-01-01',
    fastag_account: 'AC456',
    fastag_number: 'FT456',
    financier_name: 'SBI',
    fitness: { expiry_date: '2024-01-01', status: 'Valid' },
    generation: '2022',
    insurance: {
        insurance_type: 'Third Party',
        insurer_broker: 'Broker2',
        insurer_name: 'Insurance2',
        policy_end_date: '2023-01-01',
        policy_number: 'POL456',
        policy_start_date: '2022-01-01',
        premium_amount: 5000,
    },
    invoice_date: '2022-01-01',
    lease_end_date: null,
    lease_start_date: null,
    leasing_entity: null,
    ownership_count: 1,
    ownership_type: 'Owned',
    powertrain_specs: {
        ice: {
            arai_mileage_kmpl: 23,
            cng_kit_fitment_type: 'None',
            cooling_system_type: 'Liquid',
            current_mileage_kmpl: 20,
            emission_control_type: 'BS6',
            emission_norm: 'BS6',
            engine_displacement_cc: 1197,
            fuel_tank_capacity_liters: 37,
            mileage_on_start_date_kmpl: 23,
            number_of_cylinders: 4,
            transmission_type: 'Manual',
        }
    },
    puc_expiry_date: '2023-01-01',
    registration_date: '2022-01-01',
    service_config: {
        alert_interval_days: 30,
        automatic_climate_control: false,
        preventive_service_interval_days: 180,
        preventive_service_km: 10000,
        preventive_service_trigger_type: 'km',
        stepney_count: 1,
        stepney_size: 'R14',
        tyre_replacement_km: 40000,
        tyre_size: 'R14',
        wheel_alignment_km_alert_range: 5000,
    },
    state_code: 'DL',
    telematics: { enabled: false, type: 'None', name: 'None' },
    toll: { amount: 0, scope: 'National', type: 'Tag', validity_date: '2023-01-01' },
    variant: 'VXI',
    warranties: [],
  },
];
